### ISSUE TITLE
Viana Download exe?

### ISSUE THREAD

**Issue by jake765** [avosskuehler/viana#1]
Hi Viana-Team,

I have a problem with finding any setup.exe file to intall viana. Whatever version (5.5 etc) I download, there are only this strange *.wxi or *.wxiproj files which I cannot not execute on my window pc.

Do I miss something, can you help?

Thx in advance.

Best Jake

**Comment by bephial** [comment]
This is the source code in C#. You could compile it by yourself.

**Comment by bephial** [comment]
Or you just goto https://github.com/avosskuehler/viana/releases ;-)

**Comment by avosskuehler** [comment]
Thanks @bephial for your comment, sometimes the obvious isn´t ...
