### ISSUE TITLE
Viana configuration

### ISSUE THREAD

**Issue by ATePPF** [avosskuehler/viana#11]
I need to evaluate (manually) black and white videos with a large amount of black. The tracked object, in particular, is also black. Therefore, it is impossible to see the positioned tracking points. It would be good if the cursor color could be configurable.

The video comes from a high speed camera. But the framerate during playback is normal 25fps. Therefore a wrong time base is used for the calculation of the motion values. The time base should be configurable.

**Comment by avosskuehler** [comment]
I understand that having a custom cursor color which does not automatically adapt to the color of the last selected frame would be in your case a good idea, so I put it on the feature wish list ... need some time to realize it. If you have experience with WPF C# you might realize it yourself using the sources and send me a pull request.
The second suggestion should be already available. In the video info menu, there is a numeric drop down to individually specify the actual framerate, if the automatic detection fails, please try it to get your time base correct.

**Comment by avosskuehler** [comment]
Custom cursor color realized in Version 6.5 under options. Please try it.
Adrian
