### ISSUE TITLE
set orientation of x and y axis manually

### ISSUE THREAD

**Issue by Reis-A** [avosskuehler/viana#12]
In an older version, before Viana 6.0, it was required to set the orientation of the coordinate system, the x and y axis before evaluating the video. I understand that it is convenient that the x and y axis are already set in most applications.
However, when I am doing acceleration experiments on a slope, I am missing this feature.
The 90 degree rotation of the video doesn't help me, when  i want to set the x-direction parallel to the slope.
So I would really appreciate if that option was available again, or did I just didn't see that feature?

**Comment by avosskuehler** [comment]
I understand your request and will restore this feature in the next version. Please give me some time.

**Comment by avosskuehler** [comment]
Re-Realized in Version 6.5, but only right-handed coordinate system. Please try it.
Adrian
