### ISSUE TITLE
Video läuft im Hintergrund

### ISSUE THREAD

**Issue by cknodel** [avosskuehler/viana#13]
Ich habe ein Video aus der Projektsammlung gestartet. Es wird immer wieder abgespült, auch nachdem ich es (aus der Sammlung) gelöscht habe. D.h. die Tonspur läuft im Hintergrund, so lange (und sobald) Viana geöffnet ist. Bestimmt finde ich das Video irgendwo mit dem Dateimanager, aber nerven tut‘s schon…

**Comment by avosskuehler** [comment]
Hört sich nach einem nervigen Fehler an... tut mir leid. Um den Fehler zu beseitigen muss ich das Problem reproduzieren können. Was hast Du genau gemacht, welches Video, welche Buttons im Programm in welcher Reihenfolge bedient, welche Vianaversion, welches Betriebssystem?

**Comment by cknodel** [comment]
Moin Adrian, 

danke für die schnelle Nachfrage! 

Ich benutze Viana 1.2.2(2) unter iPadOS 16.1. Das Video war unter "Eines meiner bestehenden Projekte" gespeichert und auch mittels Viana aufgenommen worden (Kind auf dem Trampolin: "Quietsch..."). Das Video (bzw. dessen Tonspur) wurde in einer Schleife wiederholt, auch als ich (ich glaube mit "Projektauswahl") zur Hauptseite zurückgekehrt bin. (Ich hatte es nicht gestoppt.)  Icvh habe es dann mit dme Papierkorb-button gelöscht, aber es hat kräftig weitergequietscht.

So wie es bei mir aussieht, hat Viana keinen eigenen Ordner im Datei-Manager und ich finde keines der Viana-Videos auf der Festplatte, also auch nicht die, die von Viana angezeigt werden. (iCloud benutze ich nicht.) D.h. ich kann nicht mher nachvollziehen, ob es noch irgendwo anders auf dem Pad gespeichert war.

Ich muss gestehen, ich bin mit dem iPad nicht besonders vertraut und kann Fehlbedienung nicht ausschließen. Vor allem würde ich auf dem PC irgendwelche Dateien ziemlich sicher aufspüren, auf dem Pad nicht. 

Nach einem Neustart des iPads ist das Problem übrigens behoben. Daher kann ich das Problem leider nicht reproduzieren.

Bei aller Meckerei: Trotzdem danke für das wirklich sehr praktische Programm, das meinen Physik-Unterricht deutlich beschleunigt und bereichert! Meine Schüler stellen sich meistens auch geschickter an als ich, aber das ist ja heutzutage keine Seltenheit... 

Schöne Grüße und schönes Wochenende!

Christof

**Comment by avosskuehler** [comment]
Lieber Christof, vielen Dank für die ausführliche Anwort, leider muss ich Dich enttäuschen, für die iOS Version von Viana bin ich nicht zuständig, das sind technisch zwei völlig verschiedenen Programme, die github Seite ist für die Windows-Fassung! Da musst Du Dich wenn das Problem wieder auftaucht bitte an die Didaktik der Physik an der FU wenden.  [https://didaktik.physik.fu-berlin.de/projekte/viana/index.html](url) Viele Grüße aus Berlin, Adrian
