### ISSUE TITLE
Länge der Strecke passt nicht 

### ISSUE THREAD

**Issue by TorgeVoss** [avosskuehler/viana#14]
Ich habe die Strecke von 200cm eingegeben und eingemessen.
Bei der Auswertung der Bewegung wird die Strecke auf weniger als 50cm in der Auswertung.
Was mache ich falsch?
Oder ist es ein Fehler in der Software?
Viele Grüße Torge Voss

**Comment by avosskuehler** [comment]
Hallo Torge, ich kann das Problem bei mir nicht reproduzieren, kannst Du mir das Video, ein Screenshot Deiner Einmessung und einen Screenshot mit der Stelle des Fehlers zukommen lassen, dann kann ich nachsehen woran es liegt. Und bitte auch die benutzte Viana Version und das Betriebssystem angeben. Danke, Adrian (adrian@vosskuehler.name)

**Comment by TorgeVoss** [comment]
Vorführeffekt
Es funktioniert doch mit der Entfernung
Was nicht funktionier ist die Lage des Ursprungs 
Ursprung beim Tischtennisball
Messung erfolgt problemlos
Ausschnitt der Daten Strecke beginnt bei 1,85m und endet bei 3,55 m 
Oder ist die x-Position die richtige Auswertung?

Viele Grüße
Torge Voss

**Comment by TorgeVoss** [comment]
Betriebssystem ist Windows 10 Home
VianaNet 6.4 vom Januar 22
PS Danke für die rasche Bearbeitung
Grüße Torge

**Comment by avosskuehler** [comment]
Aus dem Video kann ich leider nicht die Datentabelle ersehen und bei GitHub sind Deine Screenshots nicht angekommen. Aber vielleicht ist es auch ein Missverständnis. Die korrekt kalibrierten Spalten müssten sowohl X-Position (Abstand in x-Richtung vom von Dir definierten Ursprung) als auch Y-Position sein. Aber auch die Streckenspalten müssten korrekt sein. Schick mir mal per Mail (nicht über Github) ein Screenshot von der Datentabelle bitte. Es könnte sein, dass bei der automatischen Erkennung der erste Datenpunkt nicht an Deinem definierten Ursprung liegt und damit die Streckenlängen davon ausgehend einen Offset haben.

**Comment by TorgeVoss** [comment]
Ja das mit dem Datenpunkt stimmt. Und die XKoordinaten passen.Danke für die Hilfe.Grüße Torge

**Comment by avosskuehler** [comment]
Prima, gern.
