### ISSUE TITLE
Recalculate speed/acceleration after downsampling

### ISSUE THREAD

**Issue by the-yrr** [avosskuehler/viana#15]
I have video files with movements of just a few pixels per frame and nearly as much noise. It would be nice to use the downsampled position values as basis for all further calculations to get much smoother curves. 

As of now downsampling the data simply removes the rows. It is not possible to recalculate the speed/acceleration using the "new" data.

**Comment by avosskuehler** [comment]
I understand your request. At the moment you have to manually remove the points to get an adapted calculation, downsampling just disables them in den graphs. I think we can modify the software such that on activated downsampling the recalculation button is valid just for the active data points. Put it on my to do list.

**Comment by avosskuehler** [comment]
Realized in Version 6.5. Please try it. 
Adrian
