### ISSUE TITLE
Kann Video von Netzlaufwerk nicht laden

### ISSUE THREAD

**Issue by deggenhof** [avosskuehler/viana#16]
![image](https://user-images.githubusercontent.com/121219824/209079747-aa1b2efc-d182-4da1-8092-0da2b326dce3.png)
Bitte um Unterstützung, wollte mit Schülern eine Videoanalyse durchführen, bekomme aber bei jedem Video eine Fehlermeldung.
<img width="497" alt="Viana" src="https://user-images.githubusercontent.com/121219824/209080671-e2377209-6836-4a43-8adb-9fe5c5799335.PNG">

**Comment by avosskuehler** [comment]
Es kann sein, dass Viana nicht ausreichend Rechte hat, um eine Datei von einem Netzlaufwerk zu öffnen. Bitte mal ausprobieren die Datei lokal zu speichern und von dort zu öffnen.

**Comment by avosskuehler** [comment]
War ein Problem mit den openCV Bibliotheken. Ist mit Version 6.6. behoben. Bitte diese verwenden und nochmal probieren. Danke.

**Comment by deggenhof** [comment]
Hallo Herr Voßkühler,

vielen Dank für die Rückmeldung.
Mit der neuen Version klappt es.

Mit freundlichen Grüßen


Alexander Hofbauer

Von: Adrian ***@***.***>
Gesendet: Mittwoch, 4. Januar 2023 19:44
An: ***@***.***>
Cc: Alexander ***@***.***>; ***@***.***>
Betreff: Re: [avosskuehler/viana] Kann Video von Netzlaufwerk nicht laden (Issue #16)


War ein Problem mit den openCV Bibliotheken. Ist mit Version 6.6. behoben. Bitte diese verwenden und nochmal probieren. Danke.
