### ISSUE TITLE
Kann mit Standalone Version keine Videos laden

### ISSUE THREAD

**Issue by Engehausen** [avosskuehler/viana#17]
Leider funktioniert Viana bei mir gar nicht. Ich habe zwar K-Light (Basic) installiert, aber nichts funktioniert. Beim Öffnen von Videos bekomme ich die Meldung unten. Welches Video-Format sollte ganz sicher ohne weitere Installationen funktionieren? Ich verwende VianaStandaloneV65x-86 unter Windows 10. Als Videos habe ich eigene und die drei Beispielvideos von der Viana-Webseite verwendet.
---

could not open 'C:\Users\Peter\Downloads\RedDot.avi'
Message: could not open 'C:\Users\Peter\Downloads\RedDot.avi'
Source: OpenCvSharp
TargetSite: Int32 <.cctor>b_1675_0(OpenCvSharp.ErrorCode, System.String, System.String, System.String, Int32, IntPtr)
StackTrace:    bei OpenCvSharp.Internal.NativeMethods.<>c.<.cctor>b_1675_0(ErrorCode Status, String funcName, String errMsg, String
fileName, Int32 line, IntPtr userData)
bei OpenCvSharp.lntemal.NativeMethods.videoio_VideoCapture_open1 (IntPtr obj, String filename, Int32 apiPreference, Int32& returnValue)
bei OpenCvSharp.VideoCapture.OpenfString fileName, VideoCaptureAPIs apiPreference)
bei VianaNET.Modules.Video.Control.VideoPlayerloadMovie(String fileName) in C:\Users\vk\VSProjects\Viana@GitHub\VianaNET\Modules \Video\Control\VideoPlayer.cs:Zeile 259.

**Comment by avosskuehler** [comment]
Im Standalone Installer war noch eine falsche opencv DLL, so dass OpenCV gar nicht von Viana geladen werden konnte. Danke für den Hinweis, ich habe die Datei direkt im Release aktualisiert (29.12.). Bitte nochmal neu herunterladen und damit probieren. Guten Rutsch!
