### ISSUE TITLE
Keines meiner Videos lässt sich in die Viana App einfügen

### ISSUE THREAD

**Issue by student0308** [avosskuehler/viana#18]
Hallo, ich kann leider kein Video in die Viana App einfügen, obwohl ich bereits verschiedene Dateiformate und sogar eines der Beispiel Videos ausprobiert habe, kriege ich immer nur eine Fehlermeldung. Woran könnte das liegen? (Ich habe auch das K-lite Codec Pack gedownloaded)
![Viana Fehlermeldung](https://user-images.githubusercontent.com/121958819/210590028-28fb052e-6e68-484a-8cd5-0f9aa7c2ab26.png)

**Comment by avosskuehler** [comment]
Waren leider die falschen Bibliotheken von openCV verlinkt, habe es korrigiert, bitte Version 6.6 verwenden.
Danke für den Hinweis!

**Comment by student0308** [comment]
Danke! Die neue Version funktioniert einwandfrei.
