### ISSUE TITLE
Danke ...

### ISSUE THREAD

**Issue by UserMica** [avosskuehler/viana#2]
... für das schöne Programm. 

Hat sehr geholfen für einer Bewegungsanalyse im Sport!

Und da einem gute Dinge besonders am Herz liegen noch drei Kommentare/Bitten:

1.  wenn es einfach ist: kann die Anzahl der "Track-Punkte" noch etwas erhöht werden (zmindest im manuellen Modus), derzeit 3 - vielleicht 5?
2. wir haben mit 60 fps Videos gearbeitet - leider hat nur die Win7 Version dieses Video akzeptiert, in allen Win10 Versionen (installer) wurde das Video konvertiert und dabei auf 25fps reduziert. Gerade bei der Analyse schneller Abläufe reicht das manchmal nicht (Videoformat: full HD, 60fps, avi, codex(?)=h264)
3. von verschiedenen Handy-Videos wurden auch die Videos falschherum angezeigt, was zwar nachträglich korrigierbar ist, den Spass aber doch etwas trübt - kann man da einen einfachen "Drehknopf" implementieren?

(wenn nötig kann ich eines meiner Videos zum Testen zur Verfügung stellen) 

**Aber wie gesagt, tolles Programm! Weiter so und vielen Dank**

**Comment by ganego** [comment]
Habe die Tage auch zum ersten Mal damit gearbeitet. Dem Punkt mit der Rotation stimme ich zu. Liegt wohl daran, dass in den mp4 Metadaten die Rotation angegeben ist. Ggf würde es reichen das zu ignorieren beim Import?
Ist der Entwickler überhaupt noch aktiv?

**Comment by avosskuehler** [comment]
Hi @UserMica  und @ganego . Es gibt mich noch, aber nur sehr sporadisch, ein Lehrerberuf und ein Programmierhobby sind nicht so gut kompatibel ... 
Punkt 1: Die Anzahl der Track-Punkte auf 5 zu erhöhen kann ich im nächsten Durchgang realisieren, ist etwas mühsam im Quellcode.
Punkt 2: Das Problem sollte sich mit Version 6 nicht mehr ergeben, die sollte auch die 60fps Videos einlesen und verarbeiten können, bitte ausprobieren.
Punkt 3: Der Drehknopf ist in Version 6 drin, ob er alles so tut wie er soll ... auch hier bitte ausprobieren und rückmelden.
Viele Grüße, schön wenn es jemand nutzt, tut mir leid, dass ich über zwei Jahre zum Antworten gebraucht habe ... nächste Mal per Mail, da schaue ich öfter hinein :-).

**Comment by avosskuehler** [comment]
Mit Version 6.1 gibt es jetzt die Möglichkeit bis zu 6 verschiedene Objekte zu tracken, das sollte reichen...
