### ISSUE TITLE
Support for windows 10?

### ISSUE THREAD

**Issue by MarkusBonsch** [avosskuehler/viana#3]
Hi,
I am trying to run VianaNet on my LENOVO Laptop under Windows 10.
I am getting the following exception (German language).

![grafik](https://user-images.githubusercontent.com/25821520/73577721-f6c61980-447d-11ea-9a3d-d8758fe124ea.png)

Does VianaNet support Windows 10? Is it still maintained and developed?
It would be a pity if this beautiful project dies . . .

Markus Bonsch

**Comment by joendter** [comment]
I don't know if this got fixed, but for me it works perfectly fine on windows 10 and I tested it on 3 different laptops.

**Comment by avosskuehler** [comment]
Hi @MarkusBonsch , the exception indicates a problem with directshow on creating the video input devices on your laptop (are there any?). In Version 6 I removed most of the directshow dependencies, cause had also problems on my recent Win10 devices, so please give the latest version a new try and let me know. 
Kind regards, Adrian

**Comment by MarkusBonsch** [comment]
Just gave it a try and it works! Great, thank you very much!
