### ISSUE TITLE
Unable to start automatic analysis without chosing a color

### ISSUE THREAD

**Issue by joendter** [avosskuehler/viana#4]
In my current project the adapt motion detection based automatic analysis works perfectly fine. Unfortunately it doesn't work at all if i don't choose a target color. So each time when I load a new (of my about 300) video-files I have to select a color to use the auto analysis. Could you please fix that?

**Comment by avosskuehler** [comment]
Hi @joendter, with version 6.1 this feature is added. Thanks for your comment.
