### ISSUE TITLE
Kompatibilität mit iPad

### ISSUE THREAD

**Issue by DavidCh03** [avosskuehler/viana#8]
Hallo,
ich benutze Viana aus dem Appstore und habe gesehen, dass es eine neuere Version gibt, Viana.NET. Ich weiß aber nicht, wie ich es auf dem iPad nutzen kann.
Ich bitte um Hilfe.

Vielen Dank

Liebe Grüße

**Comment by avosskuehler** [comment]
Hallo David, das Viana aus dem Appstore und das Viana.NET sind zwei voneinander unabhängige Softwareprojekte. Viana.NET läuft nur auf Windows Rechnern, das Viana aus dem Appstore nur auf iOS Geräten. Beide Projekte sind Nachfolger des ersten Viana von Thomas Kersting von der Uni Essen, aber eben für unterschiedliche Plattformen. Es ist sehr aufwändig und für Einzelbildanalyse von Videos im Moment in meinen Augen unmöglich eine plattformübergreifende Lösung zu programmieren, die auf Windows, iOS und am besten auch noch Android laufen würden, bin für Ideen offen. Mit Xamarin geht es zur Zeit m.E. jedenfalls nicht. Im Klartext: keine Version von Viana.NET lässt sich auf dem iPad nutzen, tut mir leid. Viele Grüße, Adrian.
